// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByO5gcV-BrDjE7-uC4kcfAnp3JTzuYS14',
    appId: '1:277416170289:android:9d01fe4ad678ac5de89610',
    messagingSenderId: '277416170289',
    projectId: 'hospital-management-c7ddc',
    storageBucket: 'hospital-management-c7ddc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGEc1bmqhPdM5ROUrHSOCDiDA4S8dNkIg',
    appId: '1:277416170289:ios:902ece24686735b6e89610',
    messagingSenderId: '277416170289',
    projectId: 'hospital-management-c7ddc',
    storageBucket: 'hospital-management-c7ddc.firebasestorage.app',
    iosBundleId: 'com.example.hospitalManagmentApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsMCNLhwFvlgSxE5Y503Zk-_jvq5_XETM',
    appId: '1:277416170289:web:94bec10d952bacece89610',
    messagingSenderId: '277416170289',
    projectId: 'hospital-management-c7ddc',
    authDomain: 'hospital-management-c7ddc.firebaseapp.com',
    storageBucket: 'hospital-management-c7ddc.firebasestorage.app',
    measurementId: 'G-47P359Z4LK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGEc1bmqhPdM5ROUrHSOCDiDA4S8dNkIg',
    appId: '1:277416170289:ios:902ece24686735b6e89610',
    messagingSenderId: '277416170289',
    projectId: 'hospital-management-c7ddc',
    storageBucket: 'hospital-management-c7ddc.firebasestorage.app',
    iosBundleId: 'com.example.hospitalManagmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsMCNLhwFvlgSxE5Y503Zk-_jvq5_XETM',
    appId: '1:277416170289:web:f206df84a210e194e89610',
    messagingSenderId: '277416170289',
    projectId: 'hospital-management-c7ddc',
    authDomain: 'hospital-management-c7ddc.firebaseapp.com',
    storageBucket: 'hospital-management-c7ddc.firebasestorage.app',
    measurementId: 'G-67TBWWHMFF',
  );

}